### ISSUE TITLE
Do a complete rewrite in python

### ISSUE THREAD

**Issue by volb** [GreenBagels/greenbot#6]
Change the code

to python

**Comment by emgram769** [comment]
I'm going to close this issue because no one helped.

  ⣀⡀ ⢀⡀   ⢀⡀ ⣀⡀ ⢀⡀   ⣇⡀ ⢀⡀ ⡇ ⣀⡀ ⢀⡀ ⢀⣸
  ⠇⠸ ⠣⠜   ⠣⠜ ⠇⠸ ⠣⠭   ⠇⠸ ⠣⠭ ⠣ ⡧⠜ ⠣⠭ ⠣⠼
